# =================== AIPass ====================
# Name: sync.py
# Description: Status sync handler — scans branches for STATUS.local.md
# Version: 1.0.0
# Created: 2026-03-10
# Modified: 2026-03-10
# =============================================

"""
Status Sync Handler

Scans all registered branches for STATUS.local.md files,
extracts state and last-update metadata, and builds an
aggregated STATUS.md at the repo root with collapsible
<details> sections per branch.

Usage (internal):
    from aipass.prax.apps.handlers.status.sync import sync_status
    result = sync_status()
"""

import json
import re
from datetime import datetime
from typing import Dict

from aipass.prax.apps.handlers.config.load import _find_repo_root
from aipass.prax.apps.modules.logger import system_logger as logger
from aipass.prax.apps.handlers.json import json_handler


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

_STATE_RE = re.compile(r"^\*\*State:\*\*\s*(.+)", re.MULTILINE)
_UPDATE_RE = re.compile(r"^\*\*Last update:\*\*\s*(.+)", re.MULTILINE)


def _extract_field(pattern: re.Pattern, text: str) -> str:
    """Return the first capture group for *pattern* in *text*, stripped."""
    match = pattern.search(text)
    if match:
        return match.group(1).strip()
    return ""


# ---------------------------------------------------------------------------
# Core
# ---------------------------------------------------------------------------

def sync_status() -> Dict:
    """
    Scan all branches for STATUS.local.md, build central STATUS.md.

    Returns:
        Dict with keys: status, branches_synced, branches_missing, timestamp
    """
    repo_root = _find_repo_root()
    registry_path = repo_root / "AIPASS_REGISTRY.json"

    if not registry_path.exists():
        logger.error("AIPASS_REGISTRY.json not found at %s", repo_root)
        return {
            "status": "error",
            "branches_synced": [],
            "branches_missing": [],
            "timestamp": datetime.now().strftime("%Y-%m-%d %H:%M"),
        }

    try:
        registry = json.loads(registry_path.read_text(encoding="utf-8"))
    except (json.JSONDecodeError, OSError) as exc:
        logger.error("Failed to read AIPASS_REGISTRY.json: %s", exc)
        return {
            "status": "error",
            "branches_synced": [],
            "branches_missing": [],
            "timestamp": datetime.now().strftime("%Y-%m-%d %H:%M"),
        }

    branches = registry.get("branches", [])

    # Collect per-branch data ------------------------------------------------
    synced = []
    missing = []
    entries = []  # (branch_email, state, date, content)

    for branch in sorted(branches, key=lambda b: b.get("email", "").lower()):
        branch_email = branch.get("email", f"@{branch.get('name', 'unknown').lower()}")
        branch_path = repo_root / branch.get("path", "")
        status_file = branch_path / "STATUS.local.md"

        if not status_file.exists():
            missing.append(branch_email)
            logger.info("STATUS.local.md missing for %s", branch_email)
            continue

        try:
            content = status_file.read_text(encoding="utf-8")
        except OSError as exc:
            missing.append(branch_email)
            logger.warning("Could not read %s: %s", status_file, exc)
            continue

        state = _extract_field(_STATE_RE, content) or "Unknown"
        last_update = _extract_field(_UPDATE_RE, content) or "n/a"

        synced.append(branch_email)
        entries.append((branch_email, state, last_update, content))

    # Tally states -----------------------------------------------------------
    state_counts: Dict[str, int] = {}
    for _, state, _, _ in entries:
        normalised = state.lower()
        state_counts[normalised] = state_counts.get(normalised, 0) + 1

    operational = state_counts.get("operational", 0)
    in_progress = state_counts.get("in progress", state_counts.get("in-progress", 0))
    not_started = state_counts.get("not started", state_counts.get("not-started", 0))

    now = datetime.now().strftime("%Y-%m-%d")

    # Build STATUS.md --------------------------------------------------------
    lines = [
        "# AIPass — System Status",
        "",
        "> Auto-generated by `drone @prax status sync`. Do not edit manually.",
        "",
        f"**Last sync:** {now}  ",
        f"**Summary:** {operational} operational | {in_progress} in-progress | {not_started} not started",
        "",
        "---",
        "",
    ]

    for branch_email, state, last_update, content in entries:
        lines.append(
            f"<details><summary><strong>{branch_email}</strong> — {state} ({last_update})</summary>"
        )
        lines.append("")
        lines.append(content.rstrip())
        lines.append("")
        lines.append("</details>")
        lines.append("")

    status_md = repo_root / "STATUS.md"
    status_md.write_text("\n".join(lines) + "\n", encoding="utf-8")

    logger.info(
        "STATUS.md synced: %d branches, %d missing", len(synced), len(missing)
    )

    json_handler.log_operation("status_synced", {"branches_synced": len(synced), "branches_missing": len(missing)})

    return {
        "status": "ok",
        "branches_synced": synced,
        "branches_missing": missing,
        "timestamp": now,
    }
