# =================== AIPass ====================
# Name: hooks_probe.py
# Description: Hook Probe Matrix Subcommand (split from hooks.py)
# Version: 1.0.0
# Created: 2026-05-16
# Modified: 2026-05-16
# =============================================

"""
Hook Probe Matrix — split from hooks.py to keep modules under 600 lines.

  hooks probe --matrix    Full event matrix + markdown report
"""

from collections import Counter, defaultdict
from pathlib import Path
from typing import Callable, List

from aipass.prax import logger
from aipass.cli import console
from aipass.seedgo.apps.handlers.file import write_text_safe
from aipass.seedgo.apps.handlers.json import json_handler
from rich.panel import Panel
from rich.table import Table


_PROBE_ENABLE_NOTE = (
    "Add probe hook commands to .claude/settings.json (inside the hooks object).\n"
    "See .claude/hooks/probes/README.md for per-event snippets."
)


def print_introspection() -> None:
    """Display module info."""
    console.print("[bold cyan]hooks_probe[/bold cyan] — matrix subcommand helper for hooks.py")
    console.print("  Not directly routable. Called via [green]drone @seedgo hooks probe --matrix[/green]")


def handle_command(command: str, args: list) -> bool:
    """Not a routed module — always returns False."""
    if not args:
        print_introspection()
        return False
    if args[0] in ("--help", "-h", "help"):
        print_introspection()
        return False
    logger.info("hooks_probe: not a routed module, command=%s args=%s", command, args)
    return False


def _build_matrix_rows(entries: list) -> tuple[list, dict]:
    """Group entries by event and build matrix row dicts. Returns (rows, groups)."""
    groups: dict = defaultdict(list)
    for e in entries:
        groups[e.get("event", "unknown")].append(e)

    matrix_rows = []
    for event_name in sorted(groups.keys()):
        evs = groups[event_name]
        count = len(evs)
        pd_true = sum(1 for e in evs if e.get("env_has_claude_project_dir"))
        pd_false = count - pd_true
        ah_true = sum(1 for e in evs if e.get("env_has_aipass_home"))
        ah_false = count - ah_true
        agents = len({e.get("agent_id", "unknown") for e in evs})
        matrix_rows.append(
            {
                "event": event_name,
                "count": count,
                "project_dir_true": pd_true,
                "project_dir_false": pd_false,
                "aipass_home_true": ah_true,
                "aipass_home_false": ah_false,
                "unique_agents": agents,
            }
        )
    return matrix_rows, groups


def _write_matrix_report(report_path: Path, matrix_rows: list, entries: list) -> None:
    """Write markdown matrix report to disk."""
    lines = [
        "# Hook Probe Matrix — Q12 Findings 2026-04-20",
        "",
        "Generated by `drone @seedgo hooks probe --matrix`.",
        "",
        f"Total entries: {len(entries)}",
        "",
        "## Event Matrix",
        "",
        "| Event | Count | ProjectDir T/F | AIPassHome T/F | Unique Agents |",
        "|-------|-------|----------------|----------------|---------------|",
    ]
    for row in matrix_rows:
        lines.append(
            f"| {row['event']} | {row['count']} "
            f"| {row['project_dir_true']}/{row['project_dir_false']} "
            f"| {row['aipass_home_true']}/{row['aipass_home_false']} "
            f"| {row['unique_agents']} |"
        )

    lines += [
        "",
        "## Notes",
        "",
        "- `ProjectDir T/F`: entries where `CLAUDE_PROJECT_DIR` env var was set (T) vs unset (F)",
        "- `AIPassHome T/F`: entries where `AIPASS_HOME` env var was set (T) vs unset (F)",
        "- Unique Agents: distinct `CLAUDE_CODE_SESSION_ID` values seen for this event",
        "",
        "## Raw entry count by event",
        "",
    ]
    event_counts = Counter(e.get("event", "unknown") for e in entries)
    for ev, cnt in sorted(event_counts.items()):
        lines.append(f"- {ev}: {cnt}")
    lines.append("")

    write_text_safe(report_path, "\n".join(lines))


def run_probe_matrix(
    read_entries: Callable[[], List[dict]],
    probes_dir: Callable[[], Path],
) -> None:
    """Group entries by event, show matrix, write markdown report."""
    entries = read_entries()

    if not entries:
        console.print(
            Panel(
                f"[yellow]No probe data yet — enable probes first.[/yellow]\n\n{_PROBE_ENABLE_NOTE}",
                title="[bold cyan][PROBE] Matrix[/bold cyan]",
                border_style="cyan",
            )
        )
        return

    matrix_rows, groups = _build_matrix_rows(entries)

    table = Table(
        title="[bold cyan][PROBE][/bold cyan] Event Matrix",
        show_header=True,
        header_style="bold cyan",
        border_style="dim",
    )
    table.add_column("Event", style="cyan", no_wrap=True)
    table.add_column("Count", justify="right", style="yellow")
    table.add_column("ProjectDir T/F", justify="center")
    table.add_column("AIPassHome T/F", justify="center")
    table.add_column("Unique Agents", justify="right")

    for row in matrix_rows:
        table.add_row(
            row["event"],
            str(row["count"]),
            f"[green]{row['project_dir_true']}[/green]/[red]{row['project_dir_false']}[/red]",
            f"[green]{row['aipass_home_true']}[/green]/[red]{row['aipass_home_false']}[/red]",
            str(row["unique_agents"]),
        )

    console.print()
    console.print(table)
    console.print()

    report_path = probes_dir() / "Q12_findings_2026-04-20.md"
    _write_matrix_report(report_path, matrix_rows, entries)
    console.print(f"[green]Report written:[/green] {report_path}\n")

    json_handler.log_operation("hooks_probe_matrix", {"events": len(groups), "total_entries": len(entries)})
