# =================== AIPass ====================
# Name: scaffold_content.py
# Description: Template content generators for aipass init scaffold
# Version: 1.0.0
# Created: 2026-04-22
# Modified: 2026-04-22
# =============================================

"""
Scaffold Content — template generators for `aipass init`

Pure string-returning functions that produce the content for each scaffold
file (CLAUDE.md, AGENTS.md, etc.). Extracted from bootstrap.py to keep
the handler under 700 lines.

RULES:
  - Pure Python only (no module/prax/cli imports)
  - Each function returns a string
  - No side effects
"""

import json
from pathlib import Path


def readme_md(name: str) -> str:
    """Generate README.md content — real getting started guide."""
    return (
        f"# {name}\n"
        "\n"
        "An AIPass project.\n"
        "\n"
        "## Quick Start\n"
        "\n"
        "```bash\n"
        "# 1. Create your first agent\n"
        "aipass init agent my_agent\n"
        "\n"
        "# 2. Start a session\n"
        "cd src/my_agent/\n"
        "claude  # or your preferred AI CLI\n"
        "\n"
        "# 3. Check project status\n"
        "cat STATUS.local.md\n"
        "```\n"
        "\n"
        "## Project Structure\n"
        "\n"
        "```\n"
        f"{name.lower()}/\n"
        f"  {name}_REGISTRY.json    # Agent registry\n"
        "  .aipass/                 # Prompts (injected per-turn)\n"
        "  CLAUDE.md               # Claude Code instructions\n"
        "  AGENTS.md               # Codex instructions\n"
        "  STATUS.local.md         # Project status\n"
        "  src/                    # Agent directories live here\n"
        "    <agent_name>/         # Created via aipass init agent\n"
        "```\n"
        "\n"
        "## What is AIPass?\n"
        "\n"
        "AIPass is a multi-agent framework where autonomous agents (citizens) "
        "live in directories with persistent identity, memory, and communication.\n"
        "\n"
        "Each agent has:\n"
        "- **Identity** — `.trinity/passport.json`\n"
        "- **Memory** — `.trinity/local.json`, `observations.json`\n"
        "- **Mailbox** — `.ai_mail.local/`\n"
        "- **Code** — `apps/` with modules and handlers\n"
        "\n"
        "## Commands\n"
        "\n"
        "| Command | Description |\n"
        "|---------|-------------|\n"
        "| `aipass init agent <name>` | Create a new agent |\n"
        "| `drone @spawn create <name>` | Create agent (alternative) |\n"
        "| `drone @seedgo audit <project>` | Run standards audit |\n"
        "| `drone @ai_mail inbox` | Check agent mailbox |\n"
        "| `drone systems` | List infrastructure |\n"
        "\n"
        f"*Initialized with [AIPass](https://github.com/AIOSAI/AIPass) on "
        f"{{date}}*\n"
    )


def global_prompt_md(name: str) -> str:
    """Generate .aipass/aipass_global_prompt.md — injected every turn."""
    return (
        f"# {name} — Project Context\n"
        "<!-- Injected every turn via hook. -->\n"
        "\n"
        "## What is AIPass\n"
        "\n"
        "AIPass is a multi-agent framework. Agents live in directories with\n"
        "persistent identity, memory, and communication. All AIPass infrastructure\n"
        "is available from any project via the `drone` command.\n"
        "\n"
        "## Terminology\n"
        "\n"
        "- **Project** — this directory. Contains a registry and agents.\n"
        "- **Agent** — a citizen with identity (`.trinity/`), memory, mailbox,\n"
        "  and code (`apps/`).\n"
        f"- **Registry** — `{name}_REGISTRY.json` tracks all agents.\n"
        "\n"
        "## Setup: if drone commands fail\n"
        "\n"
        "If `drone` cannot find the AIPass registry, set the env var:\n"
        "```bash\n"
        "export AIPASS_HOME=/path/to/AIPass   # path to AIPass installation\n"
        "```\n"
        "Add to your shell profile (`~/.bashrc` or `~/.zshrc`) to make it permanent.\n"
        "\n"
        "## Commands\n"
        "\n"
        "### Agent Lifecycle\n"
        "```\n"
        "aipass init agent <name>           # Create a new agent in src/<name>/\n"
        "drone @spawn create <name>         # Create agent (alternative)\n"
        "drone @spawn list                  # List registered agents\n"
        "```\n"
        "\n"
        "### Standards\n"
        "```\n"
        "drone @seedgo audit <project>      # Run full standards audit\n"
        "drone @seedgo checklist <file>     # Check a single file\n"
        "```\n"
        "\n"
        "### Dispatch — Send Task + Wake an Agent (DEFAULT)\n"
        "```\n"
        'drone @ai_mail dispatch @<agent> "Subject" "Body"        # Send + wake (default)\n'
        'drone @ai_mail dispatch @<agent> "Subject" "Body" --fresh # Send + wake fresh session\n'
        "drone @ai_mail dispatch wake @<agent>                    # Wake without sending\n"
        "drone @ai_mail dispatch wake --fresh @<agent>            # Wake fresh\n"
        'drone @ai_mail email @<agent> "Subject" "Body"           # FYI only (no wake)\n'
        "```\n"
        "\n"
        "Use `dispatch` by default. Use `email` only when you don't need the agent to act now.\n"
        "\n"
        "### Communication (ai_mail)\n"
        "```\n"
        "drone @ai_mail inbox               # Check your mailbox\n"
        "drone @ai_mail view <id>           # Read a message\n"
        "drone @ai_mail close <id>          # Mark message read\n"
        "```\n"
        "\n"
        "### Feedback\n"
        "```\n"
        'drone @devpulse feedback send "Subject" "Body"  # Send feedback (cross-project)\n'
        "```\n"
        "\n"
        "### Plans (flow)\n"
        "```\n"
        'drone @flow create . "Subject" dplan   # Create DPLAN (design/thinking)\n'
        'drone @flow create . "Subject" master  # Create FPLAN master (execution)\n'
        'drone @flow create . "Subject" aplan   # Create APLAN (agent-level task)\n'
        "drone @flow list open                  # List active plans\n"
        "drone @flow list                       # List all plans\n"
        "drone @flow close <id>                 # Close a plan\n"
        "drone @flow info <id>                  # View plan details\n"
        "```\n"
        "\n"
        "**DPLAN** = Dev Plan. Thinking, brainstorming, architecture decisions. "
        "Use before building.\n"
        "**FPLAN** = Flow Plan. Building and executing. Use when the plan is clear "
        "and work is underway.\n"
        "\n"
        "### Memory\n"
        "```\n"
        "drone @memory archive              # Archive memories to vector store\n"
        "drone @memory search <query>       # Search archived memories\n"
        "```\n"
        "\n"
        "### Git Workflow\n"
        "```\n"
        "drone @git pr 'description'        # Create a pull request\n"
        "drone @git status                  # Git status (branch-scoped)\n"
        "drone @git sync                    # Sync with main\n"
        "drone @git lock / unlock           # Lock/unlock the repo\n"
        "```\n"
        "\n"
        "### Infrastructure\n"
        "```\n"
        "drone systems                      # List all available infrastructure\n"
        "drone --help                       # Full drone command reference\n"
        "```\n"
        "\n"
        "## Patterns\n"
        "\n"
        "- **Communication** — agents communicate via `.ai_mail.local/`.\n"
        "- **Standards** — run `drone @seedgo audit` to check compliance.\n"
        "- **Identity** — agents have `.trinity/passport.json`. "
        "Projects use the registry.\n"
        "- **Memory** — update `.trinity/local.json` at session end. "
        "Memory is presence.\n"
        "\n"
        "## Maintenance\n"
        "\n"
        "- **Upgrade scaffold**: `drone @cli aipass init update` refreshes "
        "managed project files (hooks, prompts, settings) to latest templates.\n"
        "- **Entry point**: each agent's `apps/{name}.py` auto-configures "
        "`sys.path` and `AIPASS_BRANCH_NAME` env var. If prax logs to "
        "`unknown_branch/`, check that these are set.\n"
        "- **Standalone projects** use `src/{name}/` layout (not `src/aipass/{name}/`). "
        "Module discovery adapts automatically.\n"
    )


def gitignore() -> str:
    """Generate .gitignore content — standard AIPass ignores."""
    return (
        "# AIPass local state\n"
        ".trinity/\n"
        ".ai_mail.local/\n"
        "*.local.*\n"
        "!STATUS.local.md\n"
        "\n"
        "# Plans (local working docs)\n"
        "DPLAN-*\n"
        "FPLAN-*\n"
        "APLAN-*\n"
        "TDPLAN-*\n"
        "\n"
        "# Logs\n"
        "logs/\n"
        "\n"
        "# Python\n"
        "__pycache__/\n"
        "*.py[cod]\n"
        "*.egg-info/\n"
        "dist/\n"
        "build/\n"
        ".venv/\n"
        "venv/\n"
        "\n"
        "# IDE\n"
        ".vscode/\n"
        ".idea/\n"
        "\n"
        "# OS\n"
        ".DS_Store\n"
        "Thumbs.db\n"
        "\n"
        "# Archives\n"
        ".archive/\n"
        "\n"
        "# Disabled files\n"
        "*(disabled)*\n"
    )


def prep_md() -> str:
    """Generate .claude/commands/prep.md — /prep session wrap-up slash command."""
    return (
        "# Session Wrap-Up\n"
        "\n"
        "Purpose: Button up everything at the end of a session — or before a "
        "/compact. Memories, plans, git — all tidy. Works for both closing out "
        "a chat and preparing for compaction.\n"
        "\n"
        "**Workflow:** `/prep` → review output → close chat or `/compact`\n"
        "\n"
        "## Execution\n"
        "\n"
        "1. Read `.trinity/passport.json` first — re-absorb your identity "
        "before writing anything\n"
        "2. Do ALL of the following, then confirm what was updated\n"
        "\n"
        "## 1. Memories\n"
        "\n"
        "Each memory file plays a distinct role. Update based on what actually "
        "changed this session.\n"
        "\n"
        "- **`.trinity/passport.json`** — IDENTITY. Who you are: role, "
        "capabilities, principles. Only update if identity genuinely evolved "
        "this session.\n"
        "- **`.trinity/local.json`** — YOUR MEMORY. Add/update session entry "
        "with a summary of work done. Add key_learnings for anything learned. "
        "DO NOT trim or delete entries — rollover to @memory handles overflow automatically.\n"
        "- **`.trinity/observations.json`** — YOUR MEMORY OF THE USER. "
        "Collaboration insights, preferences, friction points. Skip if nothing "
        "new about the user this session.\n"
        "- **`STATUS.local.md`** — PUBLIC STATUS BEACON. Current work, known "
        "issues, todos, notepad. Auto-synced to central STATUS.md on PR events "
        "— this is how other branches see you. Keep Current Work accurate.\n"
        "\n"
        "## 2. Active Plans\n"
        "\n"
        "- Check any DPLANs or FPLANs referenced in this session\n"
        "- Update their execution logs, status, decision logs with current "
        "state\n"
        "- If a plan was completed, note it (but don't close — the user does "
        "that)\n"
        "\n"
        "## 3. Git State\n"
        "\n"
        "- Run `git status` — report uncommitted changes\n"
        "- If there's a logical commit waiting, suggest it (don't commit "
        "without asking)\n"
        "- Note the current branch and any open PRs\n"
        "\n"
        "## 4. Inbox\n"
        "\n"
        "- Run `drone @ai_mail inbox 2>/dev/null` — report any unread emails\n"
        "- Close any that were already processed but not formally closed\n"
        "\n"
        "## 5. Loose Ends\n"
        "\n"
        "- Flag anything in-flight: running background agents, dispatched "
        "branches waiting for replies, pending decisions\n"
        "- If anything can't survive compaction (e.g., agent IDs needed for "
        "resume), write it to STATUS.local.md Notepad\n"
        "\n"
        "## Confirm\n"
        "\n"
        "List everything updated. Format:\n"
        "```\n"
        "Prep complete:\n"
        "- local.json: [what was added]\n"
        "- observations.json: [updated / skipped]\n"
        "- STATUS.local.md: [updated / skipped]\n"
        "- Plans: [which ones updated]\n"
        "- Git: [branch, uncommitted count, suggestion]\n"
        "- Inbox: [count, action taken]\n"
        "- Loose ends: [any flagged]\n"
        "\n"
        "Ready to close out or /compact.\n"
        "```\n"
    )


def inbox_json() -> str:
    """Generate .ai_mail.local/inbox.json — empty project mailbox structure."""
    return (
        json.dumps(
            {
                "mailbox": "inbox",
                "total_messages": 0,
                "unread_count": 0,
                "messages": [],
            },
            indent=2,
            ensure_ascii=False,
        )
        + "\n"
    )


def with_source(content: str, file_path: Path) -> str:
    """Prepend a source header to AI prompt file content."""
    return f"<!-- Source: {file_path.as_posix()} -->\n{content}"
