# =================== AIPass ====================
# Name: json_structure_content.py
# Description: JSON Structure Standards Content Handler
# Version: 2.0.0
# Created: 2026-03-05
# Modified: 2026-03-17
# =============================================

"""
JSON Structure Standards Content Handler

Provides formatted JSON structure standards content.
Module orchestrates, handler implements.
"""

from aipass.seedgo.apps.handlers.json import json_handler


def get_json_structure_standards() -> str:
    """Return formatted JSON structure standards content with Rich markup.

    Returns:
        str: Formatted standards text with Rich styling
    """
    lines = [
        "[bold red]JSON STRUCTURE STANDARD[/bold red]",
        "",
        "[bold cyan]CORE PRINCIPLE:[/bold cyan] Operational JSON Output",
        "",
        "[yellow]RULE:[/yellow] Every module and handler produces operational JSON",
        "  output via json_handler. The CODE PATTERN is the standard --",
        "  not JSON file templates. Files auto-create on first use.",
        "",
        "─" * 70,
        "",
        "[bold cyan]THREE-JSON PATTERN:[/bold cyan]",
        "",
        "  Every module/handler gets 3 auto-created files:",
        "  [yellow]config.json[/yellow] - Settings, limits (small, stable)",
        "  [yellow]data.json[/yellow]   - Metrics, state (medium, periodic)",
        "  [yellow]log.json[/yellow]    - Operations history (auto-rotating)",
        "",
        "  [bold]Location:[/bold] All JSON goes to [green]{branch}_json/[/green] at branch root",
        "  [dim]src/aipass/{branch}/{branch}_json/[/dim]",
        "  One directory, no arbitrary splits.",
        "",
        "  [bold]Operator Config:[/bold] [green]{branch}_json/custom_config/[/green]",
        "  The sanctioned subdir for human-editable runtime settings.",
        "  Separates operator-tunable config from auto-generated logs/data.",
        "  [dim]Examples: cadence_config.json, memory.config.json[/dim]",
        "",
        "─" * 70,
        "",
        "[bold cyan]REQUIRED CODE WIRING:[/bold cyan]",
        "",
        "  This is the standard. This is what agents copy.",
        "",
        "  [dim]from aipass.{branch}.apps.handlers.json import json_handler[/dim]",
        "",
        "  [dim]# At end of main operations:[/dim]",
        '  [dim]json_handler.log_operation("operation_name", {[/dim]',
        '  [dim]    "key": "value",[/dim]',
        '  [dim]    "success": True[/dim]',
        "  [dim]})[/dim]",
        "",
        "  [bold]Example (flow branch):[/bold]",
        "  [dim]from aipass.flow.apps.handlers.json import json_handler[/dim]",
        "",
        '  [dim]json_handler.log_operation("plan_created", {[/dim]',
        '  [dim]    "command": command,[/dim]',
        '  [dim]    "args": args[/dim]',
        "  [dim]})[/dim]",
        "",
        "  [yellow]Both the import AND the log_operation call are required.[/yellow]",
        "  Config-only handlers log when config is accessed. If it lives in",
        "  [dim]handlers/[/dim], it logs. No exceptions — use bypass for genuine edge cases.",
        "",
        "─" * 70,
        "",
        "[bold cyan]json_handler.py SETUP:[/bold cyan]",
        "",
        "  Auto-detects branch via [dim]Path(__file__)[/dim]. Universal across branches:",
        "",
        "  [dim]_BRANCH_ROOT = Path(__file__).resolve().parents[3][/dim]",
        "  [dim]_BRANCH_NAME = _BRANCH_ROOT.name[/dim]",
        '  [dim]JSON_DIR = _BRANCH_ROOT / f"{_BRANCH_NAME}_json"[/dim]',
        "",
        "  [green]No per-branch customization needed.[/green]",
        "  Spawn ships the template, branches just copy it.",
        "",
        "  [yellow]CRITICAL:[/yellow] json_handler.py must be [bold]dependency-free[/bold].",
        "  Only stdlib imports (json, pathlib, datetime, inspect).",
        "  [red]No prax.[/red] [red]No branch imports.[/red] [red]No cli.[/red]",
        "  If a module needs to log the JSON write, the CALLER logs via prax —",
        "  not the handler. This prevents circular imports (e.g. prax → cli → json_handler → prax).",
        "",
        "─" * 70,
        "",
        "[bold cyan]VALID BYPASSES:[/bold cyan]",
        "",
        "  Some files legitimately cannot import json_handler. Add these to",
        "  [dim].seedgo/bypass.json[/dim] with a reason:",
        "",
        "  [green]•[/green] [bold]Pure-Python bootstrap files[/bold] — designed with zero branch imports",
        "    (e.g. handlers/init/bootstrap.py). Adding json_handler would break",
        "    the design contract.",
        "  [green]•[/green] [bold]Circular import chains[/bold] — if your branch has a dependency that",
        "    json_handler imports, and that dependency imports your module.",
        "    Fix: remove the dependency from json_handler (see rule above).",
        "    Bypass only if the circular import is truly unavoidable.",
        "",
        "  [dim]Example bypass entry:[/dim]",
        '  [dim]{"file": "apps/handlers/init/bootstrap.py",[/dim]',
        '  [dim] "standard": "json_structure",[/dim]',
        '  [dim] "reason": "Pure Python bootstrap — no branch imports by design"}[/dim]',
        "",
        "─" * 70,
        "",
        "[bold cyan]SCORING:[/bold cyan]",
        "",
        "  [bold]2 checks per module/handler:[/bold]",
        "  1. [dim]json_handler[/dim] import present",
        "  2. [dim]log_operation()[/dim] call present",
        "",
        "  Both must pass. Score = compliant files / total files * 100",
        "",
        "─" * 70,
        "",
        "[bold cyan]WHAT'S CHECKED:[/bold cyan]",
        "",
        "  [green]Checked:[/green]",
        "  [green]+[/green] Modules:  [dim]apps/modules/*.py[/dim]",
        "  [green]+[/green] Handlers: [dim]apps/handlers/**/*.py[/dim]",
        "  [green]+[/green] Directory: [dim]{branch}_json/[/dim] subdirs (post-audit)",
        "",
        "  [red]Skipped:[/red]",
        "  [red]-[/red] [dim]__init__.py[/dim] files (structural, not functional)",
        "  [red]-[/red] Entry points (not required to wire JSON)",
        "  [red]-[/red] [dim]json_handler.py[/dim] itself (checked for path validation only)",
        "",
        "─" * 70,
        "",
        "[bold cyan]LOG ROTATION:[/bold cyan]",
        "",
        "  Set [dim]max_log_entries[/dim] in config.json.",
        "  Handler auto-rotates when limit reached (FIFO).",
        "  Keeps most recent N entries.",
        "",
        "  [dim]{[/dim]",
        '  [dim]  "config": { "max_log_entries": 100 }[/dim]',
        "  [dim]}[/dim]",
        "",
        "─" * 70,
        "",
        "[bold cyan]DIRECTORY STRUCTURE:[/bold cyan]",
        "",
        "  [dim]{branch}_json/[/dim] is flat by default — all auto-generated JSON at root.",
        "  One sanctioned subdir: [green]custom_config/[/green] for operator-editable settings.",
        "",
        "  [dim]{branch}_json/[/dim]",
        "  [dim]├── config.json[/dim]          [dim]# auto-generated[/dim]",
        "  [dim]├── data.json[/dim]            [dim]# auto-generated[/dim]",
        "  [dim]├── log.json[/dim]             [dim]# auto-generated[/dim]",
        "  [dim]└── custom_config/[/dim]       [dim]# operator-editable[/dim]",
        "",
        "  Any other subdir is a split violation and will be flagged.",
        "  Hidden dirs (e.g. [dim].archive/[/dim]) are exempt.",
        "",
        "─" * 70,
        "",
        "[bold cyan]KEY WARNINGS:[/bold cyan]",
        "  [yellow]![/yellow]  The CODE PATTERN is the template -- no json_templates/ directory",
        "  [yellow]![/yellow]  JSON files auto-create on first log_operation() call",
        "  [yellow]![/yellow]  Never create JSON files manually",
        "  [yellow]![/yellow]  Both import AND log_operation required for compliance",
        "",
        "[bold cyan]REFERENCE:[/bold cyan]",
        "  [dim]See: seedgo standards pack (json_structure)[/dim]",
        "  [dim]See: FPLAN-0056 (Three-JSON Pattern Redesign)[/dim]",
    ]

    json_handler.log_operation("standard_content_queried", {"standard": "json_structure"})
    return "\n".join(lines)
